language: ruby
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: ruby-head
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: rbx-18mode
    - rvm: rbx-19mode
rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
notifications:
  email:
    - vijendrakarkala@gmail.com
